[config1]
REQ_PARSER_API_KEY=''
REQ_PARSER_MODEL=''
REQ_PARSER_BASE_URL=''

CON_GEN_API_KEY=''
CON_GEN_MODEL=''
CON_GEN_BASE_URL=''

CODE_GEN_API_KEY=''
CODE_GEN_MODEL=''
CODE_GEN_BASE_URL=''

REPAIR_API_KEY=''
REPAIR_MODEL=''
REPAIR_BASE_URL=''

[config2]


[current]
current = 'config1'
